### PR TITLE
Modify 01-Introduction.pptx and 02-Resources.pptx

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
These changes are only to the PPTX files; I did this so as to not have to 'recompile' the PDF and DOCX files with each commit. Feel free to merge this PR at any time or we can wait until I have gone through the whole gamut and squash all the commits into one with `recompiled` binaries.

### CODE REVIEW

**Comment by jerryaldrichiii** [comment]
Closing to make new PR

**Comment by burtlo** [comment]
All of them? The unfortunate problem with binary files is that they cannot be merged. The longer your work remains out there unmerged, the larger the chance that some work finished by others may be trampled. I would hesitate in the future from batching up the changes to a module.

**Comment by jerryaldrichiii** [comment]
I agree. Let me send in what I have so far and we'll go from there.

**Comment by burtlo** [comment]
I appreciate it @jerryaldrichiii.

**Pull request closed without merging**
